import type { InsertProperty } from '@shared/schema';

/**
 * Atlanta Metro property catalog — Sun Belt growth board.
 * Same engine fields as Philly: conditionTag drives issue count/severity,
 * propertyType drives issue pools, locationType drives urban/suburban events.
 * Gallery art lives in client/public/images/properties/atl_* (exteriors + style interiors);
 * do not change prices/rehab ranges here when updating photos.
 */
export const ATLANTA_PROPERTIES: InsertProperty[] = [
  // ——— INTTOWN URBAN ———
  {
    name: 'Cabbagetown Shotgun',
    price: 265000,
    sizeSqft: 980,
    neighborhood: 'Cabbagetown',
    rentMin: 1950,
    rentMax: 2350,
    arvMin: 310000,
    arvMax: 355000,
    conditionTag: 'Fixer-Upper',
    photoUrl: null,
    rehabMin: 48000,
    rehabMax: 92000,
    timelineMin: 8,
    timelineMax: 16,
    offMarketRate: 0.14,
    viabilityProfile: 'rehab-sinkhole',
    isActive: true,
    locationType: 'urban',
    propertyType: 'house',
    bedrooms: 2,
    bathrooms: 1,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Grant Park Bungalow',
    price: 385000,
    sizeSqft: 1450,
    neighborhood: 'Grant Park',
    rentMin: 2400,
    rentMax: 2900,
    arvMin: 440000,
    arvMax: 510000,
    conditionTag: 'Fair',
    photoUrl: null,
    rehabMin: 35000,
    rehabMax: 68000,
    timelineMin: 6,
    timelineMax: 12,
    offMarketRate: 0.12,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'urban',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 1.5,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Inman Park Victorian',
    price: 625000,
    sizeSqft: 2200,
    neighborhood: 'Inman Park',
    rentMin: 3800,
    rentMax: 4500,
    arvMin: 700000,
    arvMax: 790000,
    conditionTag: 'Good',
    photoUrl: null,
    rehabMin: 28000,
    rehabMax: 52000,
    timelineMin: 4,
    timelineMax: 8,
    offMarketRate: 0.18,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'urban',
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 2.5,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Old Fourth Ward Loft',
    price: 410000,
    sizeSqft: 1100,
    neighborhood: 'Old Fourth Ward',
    rentMin: 2800,
    rentMax: 3400,
    arvMin: 455000,
    arvMax: 520000,
    conditionTag: 'Excellent',
    photoUrl: null,
    rehabMin: 8000,
    rehabMax: 18000,
    timelineMin: 2,
    timelineMax: 4,
    offMarketRate: 0.22,
    viabilityProfile: 'rent-mirage',
    isActive: true,
    locationType: 'urban',
    propertyType: 'condo',
    bedrooms: 1,
    bathrooms: 1,
    waterSource: 'public',
    heatType: 'electric',
    metroId: 'atlanta',
  },
  {
    name: 'Midtown High-Rise Condo',
    price: 475000,
    sizeSqft: 1050,
    neighborhood: 'Midtown',
    rentMin: 3100,
    rentMax: 3700,
    arvMin: 520000,
    arvMax: 590000,
    conditionTag: 'Excellent',
    photoUrl: null,
    rehabMin: 10000,
    rehabMax: 22000,
    timelineMin: 2,
    timelineMax: 4,
    offMarketRate: 0.25,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'urban',
    propertyType: 'condo',
    bedrooms: 2,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'electric',
    metroId: 'atlanta',
  },
  {
    name: 'Edgewood Duplex',
    price: 355000,
    sizeSqft: 1680,
    neighborhood: 'Edgewood',
    rentMin: 2600,
    rentMax: 3200,
    arvMin: 410000,
    arvMax: 475000,
    conditionTag: 'Fair',
    photoUrl: null,
    rehabMin: 40000,
    rehabMax: 75000,
    timelineMin: 8,
    timelineMax: 14,
    offMarketRate: 0.15,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'urban',
    propertyType: 'duplex',
    bedrooms: 4,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'West End Craftsman',
    price: 225000,
    sizeSqft: 1320,
    neighborhood: 'West End',
    rentMin: 1750,
    rentMax: 2150,
    arvMin: 280000,
    arvMax: 340000,
    conditionTag: 'Fixer-Upper',
    photoUrl: null,
    rehabMin: 55000,
    rehabMax: 110000,
    timelineMin: 10,
    timelineMax: 18,
    offMarketRate: 0.1,
    viabilityProfile: 'time-bomb',
    isActive: true,
    locationType: 'urban',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 1,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Virginia-Highland Cottage',
    price: 520000,
    sizeSqft: 1550,
    neighborhood: 'Virginia-Highland',
    rentMin: 3200,
    rentMax: 3800,
    arvMin: 580000,
    arvMax: 650000,
    conditionTag: 'Good',
    photoUrl: null,
    rehabMin: 18000,
    rehabMax: 36000,
    timelineMin: 3,
    timelineMax: 6,
    offMarketRate: 0.16,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'urban',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'East Atlanta Bungalow',
    price: 295000,
    sizeSqft: 1180,
    neighborhood: 'East Atlanta',
    rentMin: 2100,
    rentMax: 2550,
    arvMin: 345000,
    arvMax: 400000,
    conditionTag: 'Fair',
    photoUrl: null,
    rehabMin: 32000,
    rehabMax: 60000,
    timelineMin: 6,
    timelineMax: 12,
    offMarketRate: 0.13,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'urban',
    propertyType: 'house',
    bedrooms: 2,
    bathrooms: 1,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Downtown Atlanta Studio',
    price: 195000,
    sizeSqft: 620,
    neighborhood: 'Downtown Atlanta',
    rentMin: 1600,
    rentMax: 1950,
    arvMin: 215000,
    arvMax: 250000,
    conditionTag: 'Fair',
    photoUrl: null,
    rehabMin: 15000,
    rehabMax: 32000,
    timelineMin: 3,
    timelineMax: 6,
    offMarketRate: 0.2,
    viabilityProfile: 'leverage-trap',
    isActive: true,
    locationType: 'urban',
    propertyType: 'condo',
    bedrooms: 0,
    bathrooms: 1,
    waterSource: 'public',
    heatType: 'electric',
    metroId: 'atlanta',
  },
  {
    name: 'Buckhead Tower Condo',
    price: 685000,
    sizeSqft: 1400,
    neighborhood: 'Buckhead',
    rentMin: 4200,
    rentMax: 5000,
    arvMin: 740000,
    arvMax: 840000,
    conditionTag: 'Excellent',
    photoUrl: null,
    rehabMin: 12000,
    rehabMax: 28000,
    timelineMin: 2,
    timelineMax: 4,
    offMarketRate: 0.28,
    viabilityProfile: 'rent-mirage',
    isActive: true,
    locationType: 'urban',
    propertyType: 'condo',
    bedrooms: 2,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'electric',
    metroId: 'atlanta',
  },
  {
    name: 'Grant Park Townhome',
    price: 445000,
    sizeSqft: 1720,
    neighborhood: 'Grant Park',
    rentMin: 2900,
    rentMax: 3450,
    arvMin: 500000,
    arvMax: 570000,
    conditionTag: 'Good',
    photoUrl: null,
    rehabMin: 20000,
    rehabMax: 40000,
    timelineMin: 4,
    timelineMax: 8,
    offMarketRate: 0.17,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'urban',
    propertyType: 'townhouse',
    bedrooms: 3,
    bathrooms: 2.5,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Cabbagetown Mill Duplex',
    price: 318000,
    sizeSqft: 1560,
    neighborhood: 'Cabbagetown',
    rentMin: 2450,
    rentMax: 2950,
    arvMin: 375000,
    arvMax: 430000,
    conditionTag: 'Fair',
    photoUrl: null,
    rehabMin: 38000,
    rehabMax: 70000,
    timelineMin: 7,
    timelineMax: 13,
    offMarketRate: 0.14,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'urban',
    propertyType: 'duplex',
    bedrooms: 4,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Inman Park Carriage House',
    price: 575000,
    sizeSqft: 980,
    neighborhood: 'Inman Park',
    rentMin: 3400,
    rentMax: 4000,
    arvMin: 630000,
    arvMax: 710000,
    conditionTag: 'Excellent',
    photoUrl: null,
    rehabMin: 14000,
    rehabMax: 28000,
    timelineMin: 2,
    timelineMax: 5,
    offMarketRate: 0.2,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'urban',
    propertyType: 'house',
    bedrooms: 2,
    bathrooms: 1.5,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },

  // ——— SUBURBAN / OUTLYING ———
  {
    name: 'Decatur Craftsman',
    price: 465000,
    sizeSqft: 1680,
    neighborhood: 'Decatur',
    rentMin: 2800,
    rentMax: 3350,
    arvMin: 525000,
    arvMax: 595000,
    conditionTag: 'Good',
    photoUrl: null,
    rehabMin: 22000,
    rehabMax: 42000,
    timelineMin: 4,
    timelineMax: 8,
    offMarketRate: 0.12,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Marietta Ranch',
    price: 285000,
    sizeSqft: 1520,
    neighborhood: 'Marietta',
    rentMin: 2000,
    rentMax: 2450,
    arvMin: 330000,
    arvMax: 385000,
    conditionTag: 'Fair',
    photoUrl: null,
    rehabMin: 30000,
    rehabMax: 58000,
    timelineMin: 6,
    timelineMax: 12,
    offMarketRate: 0.11,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Roswell Colonial',
    price: 545000,
    sizeSqft: 2400,
    neighborhood: 'Roswell',
    rentMin: 3100,
    rentMax: 3700,
    arvMin: 610000,
    arvMax: 700000,
    conditionTag: 'Good',
    photoUrl: null,
    rehabMin: 25000,
    rehabMax: 48000,
    timelineMin: 4,
    timelineMax: 9,
    offMarketRate: 0.15,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 2.5,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Sandy Springs Condo',
    price: 265000,
    sizeSqft: 980,
    neighborhood: 'Sandy Springs',
    rentMin: 1950,
    rentMax: 2350,
    arvMin: 295000,
    arvMax: 340000,
    conditionTag: 'Good',
    photoUrl: null,
    rehabMin: 12000,
    rehabMax: 25000,
    timelineMin: 2,
    timelineMax: 5,
    offMarketRate: 0.18,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'condo',
    bedrooms: 2,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'electric',
    metroId: 'atlanta',
  },
  {
    name: 'East Point Fixer',
    price: 175000,
    sizeSqft: 1240,
    neighborhood: 'East Point',
    rentMin: 1450,
    rentMax: 1800,
    arvMin: 230000,
    arvMax: 285000,
    conditionTag: 'Fixer-Upper',
    photoUrl: null,
    rehabMin: 60000,
    rehabMax: 115000,
    timelineMin: 12,
    timelineMax: 22,
    offMarketRate: 0.09,
    viabilityProfile: 'rehab-sinkhole',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 1,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'College Park Duplex',
    price: 248000,
    sizeSqft: 1600,
    neighborhood: 'College Park',
    rentMin: 2100,
    rentMax: 2600,
    arvMin: 300000,
    arvMax: 355000,
    conditionTag: 'Fair',
    photoUrl: null,
    rehabMin: 35000,
    rehabMax: 65000,
    timelineMin: 7,
    timelineMax: 14,
    offMarketRate: 0.12,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'duplex',
    bedrooms: 4,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Tucker Split-Level',
    price: 335000,
    sizeSqft: 1780,
    neighborhood: 'Tucker',
    rentMin: 2300,
    rentMax: 2800,
    arvMin: 385000,
    arvMax: 445000,
    conditionTag: 'Fair',
    photoUrl: null,
    rehabMin: 28000,
    rehabMax: 55000,
    timelineMin: 5,
    timelineMax: 11,
    offMarketRate: 0.11,
    viabilityProfile: 'time-bomb',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Alpharetta Townhome',
    price: 425000,
    sizeSqft: 1850,
    neighborhood: 'Alpharetta',
    rentMin: 2700,
    rentMax: 3250,
    arvMin: 475000,
    arvMax: 540000,
    conditionTag: 'Excellent',
    photoUrl: null,
    rehabMin: 10000,
    rehabMax: 22000,
    timelineMin: 2,
    timelineMax: 4,
    offMarketRate: 0.2,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'townhouse',
    bedrooms: 3,
    bathrooms: 2.5,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Smyrna Ranch',
    price: 310000,
    sizeSqft: 1480,
    neighborhood: 'Smyrna',
    rentMin: 2150,
    rentMax: 2600,
    arvMin: 355000,
    arvMax: 410000,
    conditionTag: 'Good',
    photoUrl: null,
    rehabMin: 16000,
    rehabMax: 32000,
    timelineMin: 3,
    timelineMax: 6,
    offMarketRate: 0.13,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Stone Mountain Cottage',
    price: 198000,
    sizeSqft: 1100,
    neighborhood: 'Stone Mountain',
    rentMin: 1550,
    rentMax: 1900,
    arvMin: 245000,
    arvMax: 295000,
    conditionTag: 'Fixer-Upper',
    photoUrl: null,
    rehabMin: 45000,
    rehabMax: 88000,
    timelineMin: 9,
    timelineMax: 16,
    offMarketRate: 0.1,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 2,
    bathrooms: 1,
    waterSource: 'well',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Dunwoody Contemporary',
    price: 615000,
    sizeSqft: 2600,
    neighborhood: 'Dunwoody',
    rentMin: 3600,
    rentMax: 4300,
    arvMin: 680000,
    arvMax: 770000,
    conditionTag: 'Excellent',
    photoUrl: null,
    rehabMin: 15000,
    rehabMax: 32000,
    timelineMin: 3,
    timelineMax: 6,
    offMarketRate: 0.22,
    viabilityProfile: 'leverage-trap',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 3,
    waterSource: 'public',
    heatType: 'heat_pump',
    metroId: 'atlanta',
  },
  {
    name: 'Chamblee Mid-Century',
    price: 375000,
    sizeSqft: 1620,
    neighborhood: 'Chamblee',
    rentMin: 2450,
    rentMax: 2950,
    arvMin: 425000,
    arvMax: 490000,
    conditionTag: 'Fair',
    photoUrl: null,
    rehabMin: 33000,
    rehabMax: 62000,
    timelineMin: 6,
    timelineMax: 12,
    offMarketRate: 0.14,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 3,
    bathrooms: 2,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Brookhaven Townhouse',
    price: 495000,
    sizeSqft: 1900,
    neighborhood: 'Brookhaven',
    rentMin: 3000,
    rentMax: 3600,
    arvMin: 550000,
    arvMax: 625000,
    conditionTag: 'Good',
    photoUrl: null,
    rehabMin: 18000,
    rehabMax: 35000,
    timelineMin: 3,
    timelineMax: 7,
    offMarketRate: 0.17,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'townhouse',
    bedrooms: 3,
    bathrooms: 2.5,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
  {
    name: 'Lawrenceville Colonial',
    price: 355000,
    sizeSqft: 2100,
    neighborhood: 'Lawrenceville',
    rentMin: 2250,
    rentMax: 2750,
    arvMin: 400000,
    arvMax: 460000,
    conditionTag: 'Good',
    photoUrl: null,
    rehabMin: 20000,
    rehabMax: 40000,
    timelineMin: 4,
    timelineMax: 8,
    offMarketRate: 0.12,
    viabilityProfile: 'viable',
    isActive: true,
    locationType: 'suburban',
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 2.5,
    waterSource: 'public',
    heatType: 'gas',
    metroId: 'atlanta',
  },
];
